import type { NodeDefinition, PipelineNodeType, NodeCategory } from './types';

// ======================== Node Color Scheme ========================
export const NODE_COLORS: Record<PipelineNodeType, {
  color: string;
  bg: string;
  border: string;
  text: string;
  hex: string;
  lightBg: string;
  handleColor: string;
}> = {
  'start': {
    color: 'green',
    bg: 'bg-green-50 dark:bg-green-950/30',
    border: 'border-green-400 dark:border-green-600',
    text: 'text-green-700 dark:text-green-300',
    hex: '#22c55e',
    lightBg: '#f0fdf4',
    handleColor: '#22c55e',
  },
  'end': {
    color: 'indigo',
    bg: 'bg-indigo-50 dark:bg-indigo-950/30',
    border: 'border-indigo-400 dark:border-indigo-600',
    text: 'text-indigo-700 dark:text-indigo-300',
    hex: '#6366f1',
    lightBg: '#eef2ff',
    handleColor: '#6366f1',
  },
  'trigger': {
    color: 'orange',
    bg: 'bg-orange-50 dark:bg-orange-950/30',
    border: 'border-orange-400 dark:border-orange-600',
    text: 'text-orange-700 dark:text-orange-300',
    hex: '#f97316',
    lightBg: '#fff7ed',
    handleColor: '#f97316',
  },
  'ai-process': {
    color: 'blue',
    bg: 'bg-blue-50 dark:bg-blue-950/30',
    border: 'border-blue-400 dark:border-blue-600',
    text: 'text-blue-700 dark:text-blue-300',
    hex: '#3b82f6',
    lightBg: '#eff6ff',
    handleColor: '#3b82f6',
  },
  'condition': {
    color: 'pink',
    bg: 'bg-pink-50 dark:bg-pink-950/30',
    border: 'border-pink-400 dark:border-pink-600',
    text: 'text-pink-700 dark:text-pink-300',
    hex: '#ec4899',
    lightBg: '#fdf2f8',
    handleColor: '#ec4899',
  },
  'safety': {
    color: 'emerald',
    bg: 'bg-emerald-50 dark:bg-emerald-950/30',
    border: 'border-emerald-400 dark:border-emerald-600',
    text: 'text-emerald-700 dark:text-emerald-300',
    hex: '#10b981',
    lightBg: '#ecfdf5',
    handleColor: '#10b981',
  },
  'output-node': {
    color: 'amber',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
    border: 'border-amber-400 dark:border-amber-600',
    text: 'text-amber-700 dark:text-amber-300',
    hex: '#f59e0b',
    lightBg: '#fffbeb',
    handleColor: '#f59e0b',
  },
  'plugin': {
    color: 'violet',
    bg: 'bg-violet-50 dark:bg-violet-950/30',
    border: 'border-violet-400 dark:border-violet-600',
    text: 'text-violet-700 dark:text-violet-300',
    hex: '#8b5cf6',
    lightBg: '#f5f3ff',
    handleColor: '#8b5cf6',
  },
  'rate-limit': {
    color: 'rose',
    bg: 'bg-rose-50 dark:bg-rose-950/30',
    border: 'border-rose-400 dark:border-rose-600',
    text: 'text-rose-700 dark:text-rose-300',
    hex: '#f43f5e',
    lightBg: '#fff1f2',
    handleColor: '#f43f5e',
  },
  'text-process': {
    color: 'cyan',
    bg: 'bg-cyan-50 dark:bg-cyan-950/30',
    border: 'border-cyan-400 dark:border-cyan-600',
    text: 'text-cyan-700 dark:text-cyan-300',
    hex: '#06b6d4',
    lightBg: '#ecfeff',
    handleColor: '#06b6d4',
  },
  'knowledge-base': {
    color: 'teal',
    bg: 'bg-teal-50 dark:bg-teal-950/30',
    border: 'border-teal-400 dark:border-teal-600',
    text: 'text-teal-700 dark:text-teal-300',
    hex: '#14b8a6',
    lightBg: '#f0fdfa',
    handleColor: '#14b8a6',
  },
  'webhook': {
    color: 'sky',
    bg: 'bg-sky-50 dark:bg-sky-950/30',
    border: 'border-sky-400 dark:border-sky-600',
    text: 'text-sky-700 dark:text-sky-300',
    hex: '#0ea5e9',
    lightBg: '#f0f9ff',
    handleColor: '#0ea5e9',
  },
  'code-exec': {
    color: 'slate',
    bg: 'bg-slate-50 dark:bg-slate-800/30',
    border: 'border-slate-400 dark:border-slate-600',
    text: 'text-slate-700 dark:text-slate-300',
    hex: '#64748b',
    lightBg: '#f8fafc',
    handleColor: '#64748b',
  },
  'variable-assign': {
    color: 'lime',
    bg: 'bg-lime-50 dark:bg-lime-950/30',
    border: 'border-lime-400 dark:border-lime-600',
    text: 'text-lime-700 dark:text-lime-300',
    hex: '#84cc16',
    lightBg: '#f7fee7',
    handleColor: '#84cc16',
  },
  'output-device': {
    color: 'fuchsia',
    bg: 'bg-fuchsia-50 dark:bg-fuchsia-950/30',
    border: 'border-fuchsia-400 dark:border-fuchsia-600',
    text: 'text-fuchsia-700 dark:text-fuchsia-300',
    hex: '#d946ef',
    lightBg: '#fdf4ff',
    handleColor: '#d946ef',
  },
  'replacer': {
    color: 'yellow',
    bg: 'bg-yellow-50 dark:bg-yellow-950/30',
    border: 'border-yellow-400 dark:border-yellow-600',
    text: 'text-yellow-700 dark:text-yellow-300',
    hex: '#eab308',
    lightBg: '#fefce8',
    handleColor: '#eab308',
  },
};

// ======================== Node Definitions ========================
export const NODE_DEFINITIONS: NodeDefinition[] = [
  // ---- Flow Control ----
  {
    type: 'start',
    category: 'flow-control',
    label: '开始',
    labelEn: 'Start',
    description: '流水线入口',
    descriptionEn: 'Pipeline entry point',
    icon: 'Play',
    color: 'green',
    colorHex: '#22c55e',
    bgColorClass: 'bg-green-50',
    borderColorClass: 'border-green-400',
    textColorClass: 'text-green-700',
    maxInputs: 0,
    maxOutputs: 1,
    defaultConfig: {},
    configSchema: [],
  },
  {
    type: 'end',
    category: 'flow-control',
    label: '结束',
    labelEn: 'End',
    description: '流水线出口',
    descriptionEn: 'Pipeline exit point',
    icon: 'Square',
    color: 'indigo',
    colorHex: '#6366f1',
    bgColorClass: 'bg-indigo-50',
    borderColorClass: 'border-indigo-400',
    textColorClass: 'text-indigo-700',
    maxInputs: 1,
    maxOutputs: 0,
    defaultConfig: {},
    configSchema: [],
  },
  {
    type: 'condition',
    category: 'flow-control',
    label: '条件分支',
    labelEn: 'Condition',
    description: '按条件路由消息',
    descriptionEn: 'Route messages by conditions',
    icon: 'GitBranch',
    color: 'pink',
    colorHex: '#ec4899',
    bgColorClass: 'bg-pink-50',
    borderColorClass: 'border-pink-400',
    textColorClass: 'text-pink-700',
    maxInputs: 0, // unlimited
    maxOutputs: 0, // unlimited
    defaultConfig: {
      conditions: [{ id: 'cond-1', field: '', operator: 'equals', value: '' }],
      inputPorts: [{ id: 'in-0', label: '入1' }],
      outputPorts: [{ id: 'out-0', label: '出1' }, { id: 'out-1', label: '出2' }],
    },
    configSchema: [],
  },
  // ---- Processing Stages ----
  {
    type: 'trigger',
    category: 'processing',
    label: '触发器',
    labelEn: 'Trigger',
    description: '消息过滤与预处理',
    descriptionEn: 'Message filtering & preprocessing',
    icon: 'Zap',
    color: 'orange',
    colorHex: '#f97316',
    bgColorClass: 'bg-orange-50',
    borderColorClass: 'border-orange-400',
    textColorClass: 'text-orange-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      triggerType: 'message',
    },
    configSchema: [],
  },
  {
    type: 'ai-process',
    category: 'processing',
    label: 'AI 处理',
    labelEn: 'AI Process',
    description: '大模型推理',
    descriptionEn: 'LLM processing',
    icon: 'Brain',
    color: 'blue',
    colorHex: '#3b82f6',
    bgColorClass: 'bg-blue-50',
    borderColorClass: 'border-blue-400',
    textColorClass: 'text-blue-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      runner: 'local-agent',
    },
    configSchema: [],
  },
  {
    type: 'safety',
    category: 'processing',
    label: '安全审核',
    labelEn: 'Safety',
    description: '内容安全检查',
    descriptionEn: 'Content moderation',
    icon: 'Shield',
    color: 'emerald',
    colorHex: '#10b981',
    bgColorClass: 'bg-emerald-50',
    borderColorClass: 'border-emerald-400',
    textColorClass: 'text-emerald-700',
    maxInputs: 1,
    maxOutputs: 2, // pass & fail
    defaultConfig: {
      moderationLevel: 'standard',
    },
    configSchema: [],
  },
  {
    type: 'output-node',
    category: 'processing',
    label: '输出',
    labelEn: 'Output',
    description: '响应投递',
    descriptionEn: 'Response delivery',
    icon: 'Send',
    color: 'amber',
    colorHex: '#f59e0b',
    bgColorClass: 'bg-amber-50',
    borderColorClass: 'border-amber-400',
    textColorClass: 'text-amber-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      outputFormat: 'text',
    },
    configSchema: [],
  },
  // ---- Extensions ----
  {
    type: 'plugin',
    category: 'extensions',
    label: '插件',
    labelEn: 'Plugin',
    description: '自定义扩展处理',
    descriptionEn: 'Custom extension processing',
    icon: 'Puzzle',
    color: 'violet',
    colorHex: '#8b5cf6',
    bgColorClass: 'bg-violet-50',
    borderColorClass: 'border-violet-400',
    textColorClass: 'text-violet-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      pluginName: '',
      pluginAuthor: '',
      enableAllPlugins: true,
    },
    configSchema: [],
  },
  {
    type: 'knowledge-base',
    category: 'extensions',
    label: '知识库',
    labelEn: 'Knowledge Base',
    description: 'RAG 知识检索',
    descriptionEn: 'RAG knowledge retrieval',
    icon: 'BookOpen',
    color: 'teal',
    colorHex: '#14b8a6',
    bgColorClass: 'bg-teal-50',
    borderColorClass: 'border-teal-400',
    textColorClass: 'text-teal-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      knowledgeBaseId: '',
    },
    configSchema: [],
  },
  // ---- Advanced ----
  {
    type: 'output-device',
    category: 'advanced',
    label: '输出器',
    labelEn: 'Output Device',
    description: '固定内容输出',
    descriptionEn: 'Output fixed content',
    icon: 'MessageSquare',
    color: 'fuchsia',
    colorHex: '#d946ef',
    bgColorClass: 'bg-fuchsia-50',
    borderColorClass: 'border-fuchsia-400',
    textColorClass: 'text-fuchsia-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      outputContent: '',
    },
    configSchema: [],
  },
  {
    type: 'replacer',
    category: 'advanced',
    label: '替换器',
    labelEn: 'Replacer',
    description: '替换消息关键字',
    descriptionEn: 'Replace message keywords',
    icon: 'ArrowLeftRight',
    color: 'yellow',
    colorHex: '#eab308',
    bgColorClass: 'bg-yellow-50',
    borderColorClass: 'border-yellow-400',
    textColorClass: 'text-yellow-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      replacements: [{ find: '', replace: '' }],
    },
    configSchema: [],
  },
  {
    type: 'rate-limit',
    category: 'advanced',
    label: '限流',
    labelEn: 'Rate Limit',
    description: '请求频率限制',
    descriptionEn: 'Request rate limiting',
    icon: 'Timer',
    color: 'rose',
    colorHex: '#f43f5e',
    bgColorClass: 'bg-rose-50',
    borderColorClass: 'border-rose-400',
    textColorClass: 'text-rose-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      config: { maxRequests: 10, windowSeconds: 60 },
    },
    configSchema: [
      {
        key: 'config.maxRequests',
        label: '最大请求数',
        labelEn: 'Max Requests',
        type: 'number',
        min: 1,
        max: 1000,
        defaultValue: 10,
      },
      {
        key: 'config.windowSeconds',
        label: '时间窗口 (秒)',
        labelEn: 'Window (seconds)',
        type: 'number',
        min: 1,
        max: 86400,
        defaultValue: 60,
      },
    ],
  },
  {
    type: 'text-process',
    category: 'advanced',
    label: '文本处理',
    labelEn: 'Text Process',
    description: '文本转换与格式化',
    descriptionEn: 'Text transformation & formatting',
    icon: 'FileText',
    color: 'cyan',
    colorHex: '#06b6d4',
    bgColorClass: 'bg-cyan-50',
    borderColorClass: 'border-cyan-400',
    textColorClass: 'text-cyan-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {},
    configSchema: [
      {
        key: 'config.maxLength',
        label: '最大长度',
        labelEn: 'Max Length',
        type: 'number',
        min: 1,
        defaultValue: 4096,
      },
      {
        key: 'config.truncateMethod',
        label: '截断方式',
        labelEn: 'Truncate Method',
        type: 'select',
        options: [
          { label: '尾部截断', value: 'tail' },
          { label: '中间截断', value: 'middle' },
          { label: '转为图片', value: 'image' },
        ],
        defaultValue: 'tail',
      },
    ],
  },
  {
    type: 'webhook',
    category: 'advanced',
    label: 'Webhook',
    labelEn: 'Webhook',
    description: 'HTTP 回调通知',
    descriptionEn: 'HTTP callback notification',
    icon: 'Globe',
    color: 'sky',
    colorHex: '#0ea5e9',
    bgColorClass: 'bg-sky-50',
    borderColorClass: 'border-sky-400',
    textColorClass: 'text-sky-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      webhookUrl: '',
    },
    configSchema: [
      {
        key: 'webhookUrl',
        label: 'Webhook URL',
        labelEn: 'Webhook URL',
        type: 'text',
        required: true,
        placeholder: 'https://...',
      },
    ],
  },
  {
    type: 'code-exec',
    category: 'advanced',
    label: '代码执行',
    labelEn: 'Code Exec',
    description: '自定义代码逻辑',
    descriptionEn: 'Custom code logic',
    icon: 'Code',
    color: 'slate',
    colorHex: '#64748b',
    bgColorClass: 'bg-slate-50',
    borderColorClass: 'border-slate-400',
    textColorClass: 'text-slate-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      language: 'python',
      code: '# Process the input\ndef process(data):\n    return data',
    },
    configSchema: [
      {
        key: 'language',
        label: '语言',
        labelEn: 'Language',
        type: 'select',
        options: [
          { label: 'Python', value: 'python' },
          { label: 'JavaScript', value: 'javascript' },
        ],
        defaultValue: 'python',
      },
      {
        key: 'code',
        label: '代码',
        labelEn: 'Code',
        type: 'code',
        placeholder: '# Write your code here...',
      },
    ],
  },
  {
    type: 'variable-assign',
    category: 'advanced',
    label: '变量赋值',
    labelEn: 'Variable Assign',
    description: '设置流程变量',
    descriptionEn: 'Set pipeline variables',
    icon: 'Variable',
    color: 'lime',
    colorHex: '#84cc16',
    bgColorClass: 'bg-lime-50',
    borderColorClass: 'border-lime-400',
    textColorClass: 'text-lime-700',
    maxInputs: 1,
    maxOutputs: 1,
    defaultConfig: {
      variables: [{ key: '', value: '' }],
    },
    configSchema: [
      {
        key: 'variables',
        label: '变量列表',
        labelEn: 'Variables',
        type: 'variable-list',
      },
    ],
  },
];

// ======================== Category Definitions ========================
export const NODE_CATEGORIES: Array<{
  id: NodeCategory;
  label: string;
  labelEn: string;
  icon: string;
}> = [
  { id: 'flow-control', label: '流程控制', labelEn: 'Flow Control', icon: 'Workflow' },
  { id: 'processing', label: '处理阶段', labelEn: 'Processing', icon: 'Layers' },
  { id: 'extensions', label: '扩展', labelEn: 'Extensions', icon: 'Puzzle' },
  { id: 'advanced', label: '高级', labelEn: 'Advanced', icon: 'Settings' },
];

// ======================== Helpers ========================
export function getNodeDefinition(type: PipelineNodeType): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find((d) => d.type === type);
}

export function getNodesByCategory(category: NodeCategory): NodeDefinition[] {
  return NODE_DEFINITIONS.filter((d) => d.category === category);
}

// ======================== Operator Definitions ========================
export const CONDITION_OPERATORS = [
  { label: '等于', value: 'equals' },
  { label: '不等于', value: 'not_equals' },
  { label: '包含', value: 'contains' },
  { label: '不包含', value: 'not_contains' },
  { label: '开始于', value: 'starts_with' },
  { label: '结束于', value: 'ends_with' },
  { label: '大于', value: 'greater_than' },
  { label: '小于', value: 'less_than' },
  { label: '正则匹配', value: 'regex' },
  { label: '为空', value: 'is_empty' },
  { label: '非空', value: 'is_not_empty' },
];

// ======================== Default Pipeline ========================
export const DEFAULT_PIPELINE_NODES = [
  {
    id: 'start-1',
    type: 'start',
    position: { x: 100, y: 200 },
    data: {
      label: '开始',
      description: '流水线入口',
      nodeType: 'start' as PipelineNodeType,
      config: {},
    },
  },
  {
    id: 'trigger-1',
    type: 'trigger',
    position: { x: 350, y: 200 },
    data: {
      label: '触发器',
      description: '消息过滤与预处理',
      nodeType: 'trigger' as PipelineNodeType,
      config: {},
      triggerType: 'message',
    },
  },
  {
    id: 'ai-process-1',
    type: 'ai-process',
    position: { x: 600, y: 200 },
    data: {
      label: 'AI 处理',
      description: '大模型推理',
      nodeType: 'ai-process' as PipelineNodeType,
      config: {},
      runner: 'local-agent',
    },
  },
  {
    id: 'output-1',
    type: 'output-node',
    position: { x: 850, y: 200 },
    data: {
      label: '输出',
      description: '响应投递',
      nodeType: 'output-node' as PipelineNodeType,
      config: {},
      outputFormat: 'text',
    },
  },
  {
    id: 'end-1',
    type: 'end',
    position: { x: 1100, y: 200 },
    data: {
      label: '结束',
      description: '流水线出口',
      nodeType: 'end' as PipelineNodeType,
      config: {},
    },
  },
];

export const DEFAULT_PIPELINE_EDGES = [
  { id: 'e-start-trigger', source: 'start-1', target: 'trigger-1', type: 'animated' },
  { id: 'e-trigger-ai', source: 'trigger-1', target: 'ai-process-1', type: 'animated' },
  { id: 'e-ai-output', source: 'ai-process-1', target: 'output-1', type: 'animated' },
  { id: 'e-output-end', source: 'output-1', target: 'end-1', type: 'animated' },
];
